### ISSUE TITLE
Error occurred when run `yarn start`

### ISSUE THREAD

**Issue by ghost** [n0th1ng-else/svelte-typescript-sass#1]
```
[./src/index.ts] 304 bytes {main} [built]
    + 25 hidden modules

ERROR in ./src/components/TsThing.svelte
Module build failed (from ./node_modules/svelte-loader/index.js):
Error: ParseError: Unexpected token (3:0)
1: <script lang="ts">lang;
2: "ts" >
3: ;
   ^
4: export let message;
5: /script>
    at preprocess.then.catch.err (D:\Documents\MyGit\svelte-typescript-sass\node_modules\svelte-loader\index.js:180:12)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
 @ ./src/components/App.svelte 18:0-39 27:20-27
 @ ./src/index.ts
```

**Comment by n0th1ng-else** [comment]
hey @busybruce11 I just tried to run it with yarn - it looks okay as to me.

maybe you modified file `TsThing.svelte` somehow wrong? as i can see it in console.log you send me?
i dont see any problems to appear

**Comment by n0th1ng-else** [comment]
yea i was able to reproduce it - so make sure you have valid TS code, and everything will work

**Comment by sandgupta23** [comment]
@n0th1ng-else  doesnt work

**Comment by n0th1ng-else** [comment]
could you please add more details?
